### ISSUE TITLE
Cannot get Sequelize Typings to work.

### ISSUE THREAD

**Issue by aaronbalthaser** [melxx001/simple-nodejs-typescript-starter#3]
Hi, 

First of all, nice starter. I am trying to get Seqeulize typings to work. My first attempt was to do the following:

Server ts:

`import * as ORM from 'Sequelize';`

Then npm install @types/sequelize. But when I run the server I get the error:

server.ts(7,22): error TS2307: Cannot find module 'Sequelize'.

I then attempted to install the typings the way I saw in your README.

typings install sequelize -SG. I get the error that says this cannot be installed as a global module and must be installed as an external module. So I removed the global flag and did so. I still could not use the import as syntax so I attempted to use sequelize by using the standard require. I was able to run the app but when I attempt to do the following for example:

const ORM = require('sequelize');
const sequelize = new ORM(); 

I am not getting any typescript warnings so it seems that it is not working. I am wondering if that is happening because the typings are not installed globally. How are you getting the typings to work for the other modules you have installed in typings/modules?

Any help would be nice. Thanks.

**Comment by melxx001** [comment]
Hi Aaron,

I think your issue is the Capital S in `import * as ORM from 'Sequelize';` It should work if you do `import * as ORM from 'sequelize';`

The `@types/sequelize` is for newer Typescript 2. I'm using Typescript 1 (I should upgrade it). 

Last year when I installed the typings `typings install dt~sequelize -SG`, it let me but it seems you're right that it doesn't work now. Although you don't need to install it now since by using the lowercase 'sequelize', your issue should be solved.

Let me know if that solves the issue.

**Comment by aaronbalthaser** [comment]
Thank you, much appreciated.

**Comment by melxx001** [comment]
I made a few changes in https://github.com/melxx001/simple-nodejs-typescript-starter/tree/upgrade-typescript-yarn-docker:
 - I upgraded to typescript 2
 - Started using Yarn (instead of npm) to keep installs the same. You'd need to install it globally.
 - Added some DB stuff & tests
 - I updated the Readme with information about docker & yarn. You'd need to install docker (unless you already have mysql installed, then you'd have to update the config files in the config folder with your settings.)

Can you check out the branch and let me know what you think before I merge it into master? I'm still debating whether I should keep the DB stuff since it requires an extra step to get the database up.

**Comment by aaronbalthaser** [comment]
Hey there,

Looks like a really nice setup. Again, thank you for the time spent. Personally the reason I liked your project was for the use of typescript. I am a Front-end developer mainly focused on Angular development. I am fairly familiar with backend but my new job has required me to move into full stack. So I decided to use your project to get a jump start on an API that will have public and private end points which will be accessed by other applications built from Angular using N Tier Architecture. That being said, I humbly concede that you know more about the benefits of your changes than I do. From a perspective of simplicity, adding the db setup might be better to avoid. I guess this depends on who is using your starter project as it adds complexity. Additionally, coupling your project out of the box to sql is making it more opinionated when you consider a large portion of JavaScript based applications use Mongo.

**Comment by melxx001** [comment]
Thanks for the feedback. You're right. I'll push up the changes I made to upgrading typescript & using yarn and leave the docker & db stuff in a separate branch.

If you're doing some backend work and actually need a database that is supported by sequelize, you will benefit from this docker setup where you don't have to install the db from scratch and can easily delete and re-create the whole Db should you need to reset.

Depending on how you decide to deploy this API, the config folder I put has setting for dev, test, default and production.json can be added too. My team and I decided to deploy docker

**Comment by melxx001** [comment]
Once we used docker for deployment, we passed environment variables to the npm start command instead of putting all the settings in a production.json

**Comment by aaronbalthaser** [comment]
I plan on using postgres. Unfortunately I have not had time to get up to speed with docker. I really need to do that soon. I read up on the differences between npm and yarn. Have you had a trouble installing typings with yarn?

**Comment by melxx001** [comment]
No troubles yet :) yarn works really well and seems way faster that using `npm install`

If you're starting out with this repo, I would use the latest master which now has typescript 2 and yarn.

I created another branch to contain the DB changes and the usage of Docker.

Thanks for the feedback.

**Comment by melxx001** [comment]
Closing issue. Let me know if you still need help.
